services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "${QBITTORRENT_PORT}:8080"
      - "${QBITTORRENT_CONNECTION_PORT}:6881"
      - "${QBITTORRENT_CONNECTION_PORT}:6881/udp"
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=${PROTONVPN_ENDPOINT_IP}
      - WIREGUARD_ENDPOINT_PORT=${PROTONVPN_ENDPOINT_PORT}
      - WIREGUARD_PUBLIC_KEY=${PROTONVPN_PUBLIC_KEY}
      - WIREGUARD_PRIVATE_KEY=${PROTONVPN_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${PROTONVPN_ADDRESS}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${GLUETUN_CONFIG_PATH}:/gluetun
    networks:
      - media_network
    restart: unless-stopped

  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${NZBGET_CONFIG_PATH}:/config
      - ${NZBGET_DOWNLOADS}:/downloads
    ports:
      - ${NZBGET_PORT}:6789
    restart: unless-stopped
    networks:
      - media_network

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${PROWLARR_CONFIG_PATH}:/config
    ports:
      - ${PROWLARR_PORT}:9696
    restart: unless-stopped
    networks:
      - media_network

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${RADARR_CONFIG_PATH}:/config
      - ${DATA_PATH}:/data
    ports:
      - ${RADARR_PORT}:7878
    restart: unless-stopped
    networks:
      - media_network
      
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${SONARR_CONFIG_PATH}:/config
      - ${DATA_PATH}:/data
    ports:
      - ${SONARR_PORT}:8989
    restart: unless-stopped
    networks:
      - media_network

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${QBITTORRENT_CONFIG_PATH}:/config
      - ${QBITTORRENT_DOWNLOADS}:/downloads
    depends_on:
      - gluetun
    restart: unless-stopped
      
networks:
  media_network:
    external: true