services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${RADARR_CONFIG_PATH}:/config
      - ${DATA_PATH}:/data
    ports:
      - ${RADARR_PORT}:7878
    restart: unless-stopped
    networks:
      - media_network
      
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${SONARR_CONFIG_PATH}:/config
      - ${DATA_PATH}:/data
    ports:
      - ${SONARR_PORT}:8989
    restart: unless-stopped
    networks:
      - media_network
networks:
  media_network:
    external: true