services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${RADARR_CONFIG_PATH}:/config
      - ${DATA_PATH}:/data
    ports:
      - ${RADARR_PORT}:7878
    restart: unless-stopped
    networks:
      - media_network_prod

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${PROWLARR_CONFIG_PATH}:/config
    ports:
      - ${PROWLARR_PORT}:9696
    restart: unless-stopped
    networks:
      - media_network_prod

networks:
  media_network_prod:
    external: true